1주차 미션 제출
SangWoo9734/frontend-mission pull request #1
Opened 2022-01-08 08:42 UTC by SangWoo9734

# 1주차 미션 제출 (프론트-박상우)

## 접근 방법

* [x] 미션 코드를 구현하기 위해서 어떤 생각들을 했는지 정리해보세요.
- TDD 방식으로 얼마나 구체적으로 테스트 하는 것이 적당한지
- Clean Code Guide에 따라 class, id, 변수 등 일관성있는 작명법

## 특이사항

* [x] 구현하면서 궁금했던 점이나, 아쉬웠던 부분이 있으면 적어주세요.
- v-model 과 v-bind/v-on의 차이점
- Jest 내장함수에 아직 익숙하지 못한 것
- Git 사용에 미숙한 부분  

## 제출 후 확인

* [x] 본인의 구현 결과를 `dev` 브랜치에 구현하고, `dev` 브랜치에서 `submission` 브랜치로 PR을 보내주세요.
* [x] Pull Request 생성 후 Reivewer에 @externship-master 와 @lkaybob 을 추가해주세요.

2022-01-09 14:19 UTC, lkaybob reviewed
* 요구사항을 잘 반영해주시고, CJK 언어 대응도 해주신 점이 돋보입니다.
* 테스트케이스들을 상세하게 먼저 만들어서 TDD 방법론을 실천하시려는 점이 좋아보였습니다.
* 다만, 구현체 내부를 직접 테스트하는 것은 지양하는 것을 권장드립니다.

2022-01-09 14:19 UTC, lkaybob commented on mission/tests/unit/Home.spec.js
> +        const wrapper = shallowMount(Home);
test case들에 전반적으로 Arrange, Assert, Act 단계가 구분되도록 newline들을 넣어주세요

https://next.vue-test-utils.vuejs.org/guide/essentials/a-crash-course.html#arrange-act-assert

2022-01-09 14:19 UTC, lkaybob commented on mission/src/views/Home.vue
> +      /* eslint-disable */
block 단위의 포괄적인 disable보다는 필요한 라인에 필요한 부분에만 disable을 하는 것을 권장드립니다.
* disable한 block은 검증 범위에서 제외되기 때문에 추후 불안정한 코드가 들어오더라도 검증이 안 되는 취약점을 가질 수 있기 때문입니다.
 
```
// eslint-disable-next-line no-alert
```

2022-01-09 14:19 UTC, lkaybob commented on mission/tests/unit/Home.spec.js
> +        const mockMethod = jest.spyOn(Home.methods, 'changeWord');
Vue component의 구현체를 직접 테스트하는 것은 지양해주세요.
* 구현 내부가 조금이라도 바뀌게 되면 테스트가 깨지게 됩니다.
* 아래의 링크를 통해 어떤 것을 output(검증 대상)으로 삼아야할지 참고해보세요.

https://next.vue-test-utils.vuejs.org/guide/essentials/easy-to-test.html#do-not-test-implementation-details

2022-01-09 14:19 UTC, lkaybob commented on mission/tests/unit/Home.spec.js
> +        wrapper.find('[data-word]').setValue('ProjectLion');
`setValue` 구문에 await을 사용하지면 $nextTick을 사용 안 하셔도 됩니다.

2022-01-09 14:19 UTC, lkaybob commented on mission/tests/unit/Home.spec.js
> +        expect(wrapper.vm.count).toBe(0);
vm에 직접 접근하는 것은 Vue 컴포넌트의 구현체를 직접 테스트하는 것입니다. 이런 방법은 지양해주세요.

2022-01-09 14:19 UTC, lkaybob commented on mission/package.json
> +    "package.json": "^2.0.1",
따로 추가하신 이유가 있으실까요?

2022-01-09 14:19 UTC, lkaybob commented on mission/src/App.vue
> +  <router-view />
마이너한 변경사항은 되도록이면 커밋에 들어가지 않도록 해주세요.

2022-01-09 14:43 UTC, SangWoo9734 commented on mission/package.json
> +    "package.json": "^2.0.1",
미션 시작 당시 node modules 폴더 생성을 위해서 npm install package.json을 입력하여 코드라인이 추가된 것 같습니다.

2022-01-10 02:40 UTC, 9wan6zae reviewed
그룹3 한광재입니다. 커멘트 작성완료했습니다!
### [좋은 점]
- 입력된 문자가 없을 때 버튼을 클릭하면 적절한 경고가 나온 점이 인상적이었습니다!

2022-01-10 02:40 UTC, 9wan6zae commented on mission/src/views/Home.vue
> +      }
입력된 문자가 없으면 알림을 띄워주는 기능은 좋다고 생각합니다! 다만, 커밋은 TC 설정인데 이 부분을 포함해서 기능 구현 또는 수정이 들어간 부분이 있는 것 같습니다.

2022-01-10 02:40 UTC, 9wan6zae commented on mission/src/views/Home.vue
>        this.count += 1;
요구사항에선 회전이 아닌 알림 버튼을 누른 횟수를 카운팅하는 것으로 알고 있어서 이 부분이 아쉬웠습니다.

2022-01-10 04:34 UTC, chojooyoung requested changes
상우님 안녕하세요~😀
 작성해주신 코드 너무 잘 보았습니다. 전체적으로 깔끔하게 잘 짜신것 같아요. 다만 커밋을 하실때 조금 더 세분화해서 커밋을 진행하신다면 더 깔끔한 코드가 되지 않을까 싶습니다! 1주차 너무 고생하셨어요~

2022-01-10 04:34 UTC, chojooyoung commented on mission/src/views/Home.vue
> +      <button id='word-rotate' v-on:click="rotateWord">제출</button>
해당 부분에서 v-on:click 을 @click으로 바꾸어 더 간결하게 사용 가능 할 것 같습니다!

2022-01-10 04:34 UTC, chojooyoung commented on mission/src/views/Home.vue
> +      }
광재님과 동일한 의견입니다!

2022-01-10 04:58 UTC, Yugyeong-Ji commented
그룹3의 지유경입니다!
[좋은점]
일단 전체적으로 깔끔한 것 같습니다!! 타이핑한 문자가 없다면 경고를 띄어주는 것이 좋아보였습니다!!

2022-01-10 05:01 UTC, Yugyeong-Ji commented on mission/src/views/Home.vue
> +      }
저도 동일한 의견입니다!!

2022-01-10 05:25 UTC, MiJungle commented on mission/src/views/Home.vue
> +        alert('Enter Word');
안녕하세요 박상우님! 요구된 기능 사항외에 입력된 값이 없는 상태에서 버튼 클릭 후 알림창을 구현하는 세부 기능들을 추가하신 점이 인상 깊었습니다.

2022-01-10 05:32 UTC, MiJungle commented on mission/src/views/Home.vue
> -      <input id='word_input' v-bind:value="word" v-on:input="changeWord" data-word/>
한글 입력을 고려해서 v-bind를 사용했다고 영상에서 설명해주셨는데  이 부분은 저도 몰랐던 점이라 배우고 갑니다!

2022-01-10 06:36 UTC, yeanjae0312 commented
안녕하세요 박상우님! 그룹3 이연재입니다.

[좋은점]
- input에 빈값이 들어갔을 때 경고 띄워주는 기능이 좋았습니다! 빈값시 알림창 클릭할 때마다 어색해 보였는데 해당 기능으로 어색함을 없앨 수 있을 것 같습니다 :)
- 한글이 한글자씩 밀리는 현상때문에 v-bind를 사용하신 점이 좋았습니다!

2022-01-10 06:37 UTC, yeanjae0312 commented on mission/src/views/Home.vue
>    </div>
기능구현에 대한 내용을 컴포넌트로 만들어서 적용하면 추후에 유지보수하기도 쉽고 코드도 깔끔해질 것 같아요..!

2022-01-10 06:42 UTC, yeanjae0312 commented on mission/src/views/Home.vue
> +      }
input이 빈값일 때 알림창이 띄워지면 어색했었는데 상우님처럼 경고를 띄워주는 기능을 넣어서 처리해주면 좋을 것 같네요..! 하나 배워갑니다:) 그리고 커밋에 관련된 내용은 광재님과 동일한 의견입니다!

2022-01-10 07:21 UTC, SangWoo9734 commented on mission/src/views/Home.vue
> +      }
다른 분들 피드백하면서 커밋 구성을 많이 배웠습니다! 피드백 감사합니다!

2022-01-12 05:29 UTC, merged